### ISSUE TITLE
How do I produce an initial corpus?

### ISSUE THREAD

**Issue by firelizzard18** [AdaLogics/go-fuzz-headers#88]
Go's documentation's example of a fuzz test is:

![example](https://go.dev/doc/fuzz/example.png)

I want to use go-fuzz-headers and I want to add seed corpus values that correspond to meaningful struct values. How do I do that?

**Comment by AdamKorcz** [comment]
That is a good question. I will look into that.

**Comment by finicu212** [comment]
Hello. I also am curious about this. My use case is that I am fuzzing an API based on its OpenAPI schema, and I am transforming each schema into a Go struct. Then, I want to create some random objects of those struct types, by providing the corpus with the `example` field.

For example:
```
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Dogs
```

In this case I would like to pass `1` for the `id` field, and `Dogs` for the `name` field in the corpus, for the `Category` struct type
